### ISSUE TITLE
cannot find dependance

### ISSUE THREAD

**Issue by numlauf** [NIVeriStandAdd-Ons/J1939-Custom-Device#1]
error

LabVIEW cannot find a file that is a dependency of a Startup, Exported, or Always Included VI.

File Not Found: D:\2017_HIL\NI_Instalers\NICKS\J1939-Custom-Device-master\Source\SubModules\Frame Protection Support\Source\Shared\Types\Exported Frame Type.ctl

The missing file might be referenced by one of the libraries included in the build or by the file - Initialization VI.vi. To fix this issue:

- Open all Startup, Exported, or Always Included VIs, recompile them (CTRL+SHIFT Click the Run arrow) and save them to update their dependencies.

Click the link below to visit the Application Builder support page. Use the following information as a reference:

Error 7 occurred at AB_Engine_HandleLinkErrors.vi -> AB_Engine_Update_Source_from_Linker.vi

Possible reason(s):

LabVIEW:  File not found. The file might be in a different location or deleted. Use the command prompt or the file explorer to verify that the path is correct.
=========================
NI-488:  Nonexistent GPIB interface.

im also missing the folowing from the snip
![image](https://user-images.githubusercontent.com/8400066/50618414-24761300-0eb8-11e9-8f7d-53ba940306a3.png)

**Comment by eatondan** [comment]
You need to download the Submodule. 
https://github.com/NIVeriStandAdd-Ons/Frame-Protection-Support

If you are using a client, you can right click on the main folder and select Submodule Update...
